apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpt3-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gpt3
  template:
    metadata:
      labels:
        app: gpt3
    spec:
      containers:
        - name: gpt3-container
          image: scottlaiq/gpt3-app:latest
          ports:
            - containerPort: 8080
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai-api-key
                  key: api-key



